version: '2'

services:

  db:
    image: mariadb:latest
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=mythtv
      - MYSQL_DATABASE=mythtv
      - MYSQL_USER=mythtv
      - MYSQL_PASSWORD=mythtv
    volumes:
      - ./db/data:/var/lib/mysql

  mythtv:
    build: ./mythtv
    container_name: mythtv
    ports:
      - "8069:8069"
    links:
      - db:db
    depends_on:
      - db
    tty: true
    environment:
      - PGHOST=db
      - PGUSER=odoo
      - PGPASSWORD=odoo
